#!/usr/bin/env bash
# ==================================================
# Build Script
# Why: รวม module หลายไฟล์เป็นไฟล์เดียวสำหรับ distribution
#      รองรับ auto-load จาก core/data/features
# ==================================================

# Why: strict mode เพื่อหยุดทันทีเมื่อ build พลาด
set -euo pipefail

# Why: หา root directory ของโปรเจกต์
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Why: กำหนด path ของไฟล์ผลลัพธ์
DIST_DIR="$ROOT_DIR/dist"
OUT_FILE="$DIST_DIR/sshplus.sh"

# Why: log info สำหรับ build process
log_info() {
  echo "[INFO] $*"
}

# Why: จบ build เมื่อพบ error
die() {
  echo "[ERROR] $*" >&2
  exit 1
}

# Why: ล้าง dist เก่าเพื่อให้ build artifact สะอาดเสมอ
prepare_dist() {
  rm -rf "$DIST_DIR"
  mkdir -p "$DIST_DIR"
}

# Why: เขียน header ของไฟล์ distribution
write_header() {
  cat > "$OUT_FILE" <<'HEADER'
#!/usr/bin/env bash
# ==================================================
# SSHPlus Manager - Single-file Distribution
# Generated by scripts/build.sh
# ==================================================

# Why: strict mode สำหรับ runtime
set -u
set -o pipefail

# Why: locale คงที่
export LC_ALL=C

# Why: umask ปลอดภัย
umask 077
HEADER
}

# Why: เพิ่ม module หนึ่งไฟล์ โดยตัด shebang ทิ้ง และบังคับ newline หลังไฟล์
append_module() {
  local module="$1"
  local full_path="$ROOT_DIR/$module"

  if [[ ! -f "$full_path" ]]; then
    die "Missing module: $module"
  fi

  log_info "Appending $module"

  # Why: ตัด shebang ของ module ออก เพราะไฟล์รวมมี shebang เดียว
  sed -e '1{/^#!/d}' "$full_path" >> "$OUT_FILE"

  # Why: บังคับ newline หลังแต่ละ module
  printf '\n' >> "$OUT_FILE"
}

# Why: เพิ่ม modules ทั้งหมดจาก directory ที่กำหนด
add_modules_from_dir() {
  local dir="$1"
  local full_dir="$ROOT_DIR/$dir"

  if [[ ! -d "$full_dir" ]]; then
    return 0
  fi

  local file_path
  local relative_path

  while IFS= read -r -d '' file_path; do
    relative_path="${file_path#"$ROOT_DIR"/}"
    MODULES+=("$relative_path")
  done < <(find "$full_dir" -type f -name '*.sh' -print0 | sort -z)
}

# Why: รวบรวม module ทั้งหมดตามลำดับการโหลด
collect_modules() {
  MODULES=()

  # Why: core ต้องโหลดก่อน
  add_modules_from_dir "src/lib/core"

  # Why: data layer โหลดหลัง core
  add_modules_from_dir "src/lib/data"

  # Why: features โหลดหลัง data
  add_modules_from_dir "src/lib/features"

  # Why: main ต้องโหลดหลังสุด
  MODULES+=("src/main.sh")
}

# Why: วนรวมทุก module ตามลำดับที่กำหนด
append_modules() {
  local module

  for module in "${MODULES[@]}"; do
    append_module "$module"
  done
}

# Why: เพิ่ม main dispatcher ตอนท้ายของไฟล์ distribution
append_entrypoint_call() {
  printf '\nmain "$@"\n' >> "$OUT_FILE"
}

# Why: ตั้งสิทธิ์ให้ไฟล์ dist รันได้
make_executable() {
  chmod 755 "$OUT_FILE" 2>/dev/null || true
}

# Why: สร้าง checksum สำหรับตรวจสอบความสมบูรณ์ของ artifact
write_checksum() {
  (
    cd "$DIST_DIR"

    if command -v sha256sum >/dev/null 2>&1; then
      sha256sum sshplus.sh > sshplus.sh.sha256
    elif command -v shasum >/dev/null 2>&1; then
      shasum -a 256 sshplus.sh > sshplus.sh.sha256
    else
      log_info "No sha256 tool found. Skip checksum."
    fi
  )
}

# Why: orchestrate build ทั้งหมด
main() {
  prepare_dist
  write_header
  collect_modules
  append_modules
  append_entrypoint_call
  make_executable
  write_checksum
  log_info "Build completed: $OUT_FILE"
}

main "$@"
